add_library(dungeon_geometry_generator_check STATIC
    check.cpp
)

target_include_directories(dungeon_geometry_generator_check PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(dungeon_geometry_generator_check PUBLIC dungeon_geometry_generator dungeon_geometry_generator_fill pgg)
target_compile_features(dungeon_geometry_generator_check PUBLIC cxx_std_20)
